# Site settings
title: Omnicon
email: info@omnicononline.com
description: "Omnicon returns, the best pop-culture convention in south Texas! Awesome vendors, voice actors, and cosplay at an unforgettable event, August 5-6, 2016"
baseurl: ""
url: "http://omnicononline.com"
twitter_username: omnicononline
facebook_username: omniconconvention
github_username:  bentsea

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
encoding: utf-8
